UNZIP Undeflates, Unreduces, Unshrinks, Unimplodes and Unstores, files 
from MS-DOS ZIP files.  Ether checks CRCs or extracts files specified.  
Applies stored date stamps to extracted files on systems that support date 
stamping.  Accepts DU and DIR specs for ZIP file and as destination for 
extracted files. Output filenames are supported.  Can be aborted with ^C 
without leaving partial files on disk.  Outputs sizes, version, method, 
datestamp and CRC for each file processed
  -- Lars Nelson 12/05/20
